Initial Commit

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -5,7 +5,6 @@ workflows:
     react-native-android:
         name: React Native Android
         max_build_duration: 120
-        instance_type: mac_pro
         environment:
             vars:
                 # https://firebase.google.com/docs/cli#cli-ci-systems
@@ -22,58 +21,58 @@ workflows:
                 - tag
                 - pull_request
             branch_patterns:
-                - pattern: develop
+                - pattern: react
                   include: true
                   source: true
         scripts:
             - name: Install npm dependencies
               script: |
                 npm install
-            - name: Set Android SDK location
-              script: |
-                echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
-            - name: Set up keystore
-              script: |
-                    echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
-                    cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
-                    storePassword=$CM_KEYSTORE_PASSWORD
-                    keyPassword=$CM_KEY_ALIAS_PASSWORD
-                    keyAlias=$CM_KEY_ALIAS_USERNAME
-                    storeFile=/tmp/keystore.keystore
-                    EOF
+            # - name: Set Android SDK location
+              # script: |
+                # echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
+            # - name: Set up keystore
+              # script: |
+                    # echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
+                    # cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
+                    # storePassword=$CM_KEYSTORE_PASSWORD
+                    # keyPassword=$CM_KEY_ALIAS_PASSWORD
+                    # keyAlias=$CM_KEY_ALIAS_USERNAME
+                    # storeFile=/tmp/keystore.keystore
+                    # EOF
             - name: Build Android release
               script: |
                 # build Android
                 cd android
                 ./gradlew assembleRelease
-            - name: Firebase App Distribution
-              script: |
+            # - name: Firebase App Distribution
+              # script: |
                 # https://firebase.google.com/docs/app-distribution/android/distribute-cli
                 #!/usr/bin/env sh
-                set -e   # exit on first failed command
-                set -x   # print all executed commands to the log
+                # set -e   # exit on first failed command
+                # set -x   # print all executed commands to the log
                 
                 # Android Firebase App Distribution CLI
                 # Change the --app value below!!
 
-                firebase appdistribution:distribute $FCI_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk \
-                --app 1:831201993789:android:b9039e5b4d34d88754f271 \ 
-                --token "$FIREBASE_TOKEN" \
-                --release-notes "Internal Android test release" \
-                --groups "cmrnapp-testers"
+                # firebase appdistribution:distribute $FCI_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk \
+                # --app 1:831201993789:android:b9039e5b4d34d88754f271 \ 
+                # --token "$FIREBASE_TOKEN" \
+                # --release-notes "Internal Android test release" \
+                # --groups "cmrnapp-testers"
         artifacts:
             - android/app/build/outputs/**/*.apk
         publishing:
             email:
                 recipients:
-                    - user@example.io
+                    - stephen.olabode@nautilus.tech
     react-native-ios:
         name: React Native iOS
         max_build_duration: 120
-        instance_type: mac_pro
+        instance_type: mac_mini
         environment:
             vars:
-                FIREBASE_TOKEN: Encrypted(...) # <-- Put your encrypted Firebase App Distribution CI token here
+                # FIREBASE_TOKEN: Encrypted(...) # <-- Put your encrypted Firebase App Distribution CI token here
                 XCODE_WORKSPACE: "codemagicreactnative.xcworkspace" # <-- Put the name of your Xcode workspace here
                 XCODE_SCHEME: "codemagicreactnative" # <-- Put the name of your Xcode scheme here
                 # Manual Code Signing
@@ -84,10 +83,10 @@ workflows:
                 # Automatic Code Signing 
                 # https://docs.codemagic.io/yaml/distribution/
                 # https://appstoreconnect.apple.com/access/api
-                APP_STORE_CONNECT_ISSUER_ID: 5a451239-51eb-10b6-bfcc-60e61ddab13c # <-- Put your App Store Connect Issuer Id here
-                APP_STORE_CONNECT_KEY_IDENTIFIER: LY55E1G322 # <-- Put your App Store Connect Key Identifier here
-                APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # <-- Put your App Store Connect Private Key here
-                CERTIFICATE_PRIVATE_KEY: Encrypted(...) # <-- Put your Certificate Private key here
+                # APP_STORE_CONNECT_ISSUER_ID: 5a451239-51eb-10b6-bfcc-60e61ddab13c # <-- Put your App Store Connect Issuer Id here
+                # APP_STORE_CONNECT_KEY_IDENTIFIER: LY55E1G322 # <-- Put your App Store Connect Key Identifier here
+                # APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # <-- Put your App Store Connect Private Key here
+                # CERTIFICATE_PRIVATE_KEY: Encrypted(...) # <-- Put your Certificate Private key here
             node: latest
             xcode: latest
             cocoapods: default
@@ -97,7 +96,7 @@ workflows:
                 - tag
                 - pull_request
             branch_patterns:
-                - pattern: develop
+                - pattern: react
                   include: true
                   source: true
         scripts:
@@ -107,9 +106,9 @@ workflows:
             - name: Install CocoaPods dependencies
               script: |
                 cd ios && pod install
-            - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
-              script: |
-                keychain initialize
+            # - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
+              # script: |
+                # keychain initialize
             # - name: Set up Provisioning profiles from environment variables (Use with manual code signing)
             #   script: |
             #     PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
@@ -142,20 +141,20 @@ workflows:
             - name: Build ipa for distribution
               script: |
                 xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
-            - name: Firebase App Distribution
-              script: |
+            # - name: Firebase App Distribution
+              # script: |
                 #!/usr/bin/env sh
-                set -e   # exit on first failed command
-                set -x   # print all executed commands to the log
+                # set -e   # exit on first failed command
+                # set -x   # print all executed commands to the log
                 
                 # iOS Firebase App Distribution CLI
                 # Change the --app value below!!
 
-                firebase appdistribution:distribute $FCI_BUILD_DIR/build/ios/ipa/codemagicreactnative.ipa \
-                --app 1:830101873788:ios:05df72817d62e45253f229 \
-                --token "$FIREBASE_TOKEN" \
-                --release-notes "Internal iOS test release" \
-                --groups "cmrnapp-testers"   
+                # firebase appdistribution:distribute $FCI_BUILD_DIR/build/ios/ipa/codemagicreactnative.ipa \
+                # --app 1:830101873788:ios:05df72817d62e45253f229 \
+                # --token "$FIREBASE_TOKEN" \
+                # --release-notes "Internal iOS test release" \
+                # --groups "cmrnapp-testers"   
         artifacts:
             - build/ios/ipa/*.ipa
             - /tmp/xcodebuild_logs/*.log
